### ISSUE TITLE
Integrate with semu

### ISSUE THREAD

**Issue by redhog** [sysprog21/shecc#100]
* [ ] Port semu to the shecc subset of c
* [ ] Use semu instead of qemu in bootstrapping

**Comment by jserv** [comment]
I am concluding this discussion for several reasons: Firstly, semu is a transitional project that will ultimately be integrated into [rv32emu](https://github.com/sysprog21/rv32emu). Secondly, both semu and rv32emu utilize complex C programming features, like designated initializers, which shecc probably can not support. Thirdly, as shecc is compatible with both RV32 and Arm32, qemu is better suited for initial setup, especially for userspace emulation, whereas semu is restricted to RV32 system emulation.

**Comment by redhog** [comment]
How does semu relate to rv32emu?

**Comment by redhog** [comment]
Just trying to see how this aligns with my goals:

I want to have/build an emulator that is capable of booting a full linux that is as small as possible /and/ that is written in as small a subset of a language as possible. That is, getting from knowing nothing of even the language to understanding the whole emulator should be as fast/easy as possible. As an additional validation, I want to also have a compiler (or interpreter) for the same language, written in the same language and with the same properties of minimal and easy to understand. Speed and optimization (JIT and similar techniques) are from that perspective a distraction. As is e.g. nerwork device emulation.

This seem to fit with what you have already built so far, but not with your end goals? I guess the easiest path to this is to fork your work then?

**Comment by jserv** [comment]
> This seem to fit with what you have already built so far, but not with your end goals? I guess the easiest path to this is to fork your work then?

I am a university faculty member, and my primary drive for creating these repositories is to establish a testing ground for my students. They have the opportunity to build upon my work, which I believe is essential for their engineering education. This has been my approach for several years. Feel free to fork the repository and submit pull requests if you find anything valuable to add. I value discussions about this work, especially from those who haven't taken my course.
