### ISSUE TITLE
The peephole optimization breaks the macro expansion

### ISSUE THREAD

**Issue by vacantron** [sysprog21/shecc#112]
Considering the following test case:

```c
#define M(a, b) a + b

int main()
{
    return M(1, 2) * 3;
}
```

The stage-1 shecc (i.e. out/shecc-stage1.elf, testing with command: `qemu-arm out/shecc-stage1.elf --no-libc <file>`) reports:

```shell
Error Unexpected token at source location 20
#define M(a, b) a + b
                    ^ Error occurs here
Abnormal program termination
```

The current test driver runs on the stage-0 shecc and doesn't detect this error.

**Comment by jserv** [comment]
> The current test driver runs on the stage-0 shecc and doesn't detect this error.

Shall we enable extra stage-1 check in CI pipeline?

**Comment by vacantron** [comment]
> Shall we enable extra stage-1 check in CI pipeline?

I think not. The stage-1 check needs to self-host first, but the current workflow only invokes the unit test.

This problem is caused by the uncovered scenario in the test driver. We can refine the test driver to detect this problem.
