### ISSUE TITLE
Support macros defined in <stdbool.h>

### ISSUE THREAD

**Issue by jserv** [sysprog21/shecc#122]
C99 introduces a built-in type called `_Bool` for handling Boolean values. Additionally, the standard header `<stdbool.h>` defines macros `bool`, `true`, and `false` to facilitate boolean operations. 

As per C99's specifications, except for bit-fields, all data types, including bool, must be allocated at least one byte of memory. This allocation ensures that objects consist of contiguous byte sequences, the specifics of which depend on the implementation or are explicitly stated. Since a `char`'s size is universally one byte, it follows logically that the size of a `bool` must also be one byte, at most. In summary, based on C99 standards, the size of a `bool` is definitively set to one byte.

Incorporating the `bool` type into shecc would enhance the expressiveness of source code and improve memory usage when expressions solely need to represent binary relationships.

C99 6.2.6.1 General
> Except for bit-fields, objects are composed of contiguous sequences of one or more bytes, the number, order, and encoding of which are either explicitly specified or implementation-defined.

C99 6.3.1.1 Boolean, characters, and integers
> The rank of `_Bool` shall be less than the rank of all other standard integer types.

**Comment by ChAoSUnItY** [comment]
should these macros be defined in another file e.g. `stdbool.c` rather than `c.c`?

**Comment by jserv** [comment]
> should these macros be defined in another file e.g. `stdbool.c` rather than `c.c`?

No, maintaining our copy of `<stdbool.h>` is not necessary. By leveraging the shecc-specific identifier (`__SHECC__`), we can easily define the `bool`-related macros directly in `src/defs.h`, thereby ensuring our implementation adheres to C99 standards.

**Comment by ChAoSUnItY** [comment]
After further investigation by utilize `bool` back on declarations, e.g. return type / parameter type in functions (see bb677b4a5af2f0c29cdf7a08cf4ad8a7b7955e1d), I found that the issue that caused stage 2 compilation failure is the global variable initialization with bool type, specifically [this one](https://github.com/ChAoSUnItY/shecc/commit/bb677b4a5af2f0c29cdf7a08cf4ad8a7b7955e1d#diff-cb04b2b9e0266d9c19d802ec012b6ac8e203765345e8cf86d3be88c24501bc1fR86). By replacing `int` with `bool`, the stage 2 compilation would fail.

I think this is not frontend but codegen's fault?

**Comment by vacantron** [comment]
This problem is probably caused by the unmatched size of the datatype when allocating variable in either https://github.com/sysprog21/shecc/blob/cb49429f21c7dc0b971836e44d4d47a0a15894e5/src/reg-alloc.c#L259-L265
or https://github.com/sysprog21/shecc/blob/cb49429f21c7dc0b971836e44d4d47a0a15894e5/src/reg-alloc.c#L347-L352

We need to check the type `bool` also.

BTW, can we simply replace the macro in `lib/c.c`
https://github.com/sysprog21/shecc/blob/cb49429f21c7dc0b971836e44d4d47a0a15894e5/lib/c.c#L12
with
```diff
- type = add_named_type("_Bool");
+ type = add_named_type("bool");
```
at `src/parser.c` ?
https://github.com/sysprog21/shecc/blob/cb49429f21c7dc0b971836e44d4d47a0a15894e5/src/parser.c#L2882

The current preprocessor only support number or string if it is not a function-like macro.

**Comment by ChAoSUnItY** [comment]
Current macro supports identifier macro but only "_Bool" will be supported at this moment
https://github.com/sysprog21/shecc/blob/cb49429f21c7dc0b971836e44d4d47a0a15894e5/src/parser.c#L391-L394
https://github.com/sysprog21/shecc/blob/cb49429f21c7dc0b971836e44d4d47a0a15894e5/src/lexer.c#L524-L530

And I will rework on frontend tokenizing process recently to hopefully eliminate some unintentional limitations, e.g. single token aliasing in macro.
