### ISSUE TITLE
Unable to self compile stage 1

### ISSUE THREAD

**Issue by ChAoSUnItY** [sysprog21/shecc#123]
In commit 5f4f6d65b6670b8ac01bde5055da6075ed09a10a, by applying the following command `make distclean config ARCH=arm` and then `make` to build stage 1 compiler, the compiler will report unexpected token error at unreasonable position:
```
Error Unexpected token at source location 20771
    ref_block_t *head, *tail;
                       ^ Error occurs here
```

**Comment by jserv** [comment]
It was my mistake to push the unintended changes. I will create the issues associated with the declaration changes.
