### ISSUE TITLE
Fail to pass stage1

### ISSUE THREAD

**Issue by jserv** [sysprog21/shecc#125]
commit 5979cb8d7a246f2d0818bca972468ab9c8a77460 introduces preliminary support of C99 `_Bool`. However, it fails to pass stage1:
```
$ make 
  SHECC	out/shecc-stage1.elf
Aborted (core dumped)
make: *** [Makefile:80: out/shecc-stage1.elf] Error 134
```

Tested on Ubuntu 20.04.6 LTS.

**Comment by jserv** [comment]
> ```c
> #define HOST_PTR_SIZE __SIZEOF_POINTER__
>                       ^ Error occurs here
> Abnormal program termination
> ```
> I am uncertain if this issue is caused by current design or previous design flaw?

This effort by @vacantron last year was aimed at achieving self-hosting.

**Comment by ChAoSUnItY** [comment]
After investigate the diff from 5979cb8d7a246f2d0818bca972468ab9c8a77460 and 7f328f33a97d21096d36340f773f16cffc714cce by implementing functionalities step-by-step, I found that by replacing boolean related symbols, e.g. replacing `int` with `bool`, the stage-2 compilation would failed at `#define HOST_PTR_SIZE __SIZEOF_POINTER__`, which is unexpected consider nothing more than returning type and value is changed.

I will submit a hot fix by reverting previous PR #124 and implement back the necessary macro definitions.

**Comment by jserv** [comment]
> I will submit a hot fix by reverting previous PR #124 and implement back the necessary macro definitions.

Can you rework the `_Bool` support instead?

**Comment by ChAoSUnItY** [comment]
By commit changes on latest commit which discards changes that causes building failure?

**Comment by jserv** [comment]
> By commit changes on latest commit which discards changes that causes building failure?

There is no need to discard or revert existing commits such as 5979cb8d7a246f2d0818bca972468ab9c8a77460. Simply ensure the `_Bool` support functions as intended by submitting new commits.
