### ISSUE TITLE
For a coding question: about parser

### ISSUE THREAD

**Issue by ChenMiaoi** [sysprog21/shecc#129]
**I would like to ask, in parser, is "shecc" a directly generated instruction set linked list sequence? I don't seem to have found the relevant code for AST. If so, please point out.**

If possible, may you comment on each structure and field in def.h?

Heartfelt thanks.

**Comment by jserv** [comment]
By the way, the book [Parsing Techniques: A Practical Guide 2/e](https://www.amazon.com/Parsing-Techniques-Practical-Monographs-Computer/dp/1441919015) offers valuable insights into the inner workings of compilers and is a highly recommended resource for those interested in learning more about this topic.

**Comment by ChenMiaoi** [comment]
Thanks. I'll read this.
