### ISSUE TITLE
Unable to perform implicit value casting

### ISSUE THREAD

**Issue by ChAoSUnItY** [sysprog21/shecc#162]
By compling code the following code with shecc, shecc would immediately abort without any reason given:
```c
typedef struct {
    int pos;
    char source[100];
    int source_len;
} lexer_t;

char lexer_peek_char(lexer_t *lexer, int offset) {
    if (lexer->pos + offset >= lexer->source_len)
        return '\0';

    return lexer->source[lexer->pos + offset];
}

int main() {
    return 1;
}
```

However, by removing the boundary check in `lexer_peek_char`, the code would be compiled successfully:
```c
typedef struct {
    int pos;
    char source[100];
    int source_len;
} lexer_t;

char lexer_peek_char(lexer_t *lexer, int offset) {
    return lexer->source[lexer->pos + offset];
}

int main() {
    return 1;
}
```

**Comment by DrXiao** [comment]
@ChAoSUnItY, I modified and compiled your code, and the compilation was successful.
```diff
typedef struct {
    int pos;
    char source[100];
    int source_len;
} lexer_t;

char lexer_peek_char(lexer_t *lexer, int offset) {
    if (lexer->pos + offset >= lexer->source_len)
-       return '0';
+       return 0;

    return lexer->source[lexer->pos + offset];
}

int main() {
    return 1;
}
```
I think that **shecc currently lacks the ability to handle character literals as return values.**

Thus, if we want shecc to compile the original test code, the frontend needs improvement.

**Comment by ChAoSUnItY** [comment]
After further investigation, I found that this is not caused by value casting, instead, shecc didn't implements escaped NULL character `\0` in lexer.

https://github.com/sysprog21/shecc/blob/affa4fc637b15b4bab7415fbe7a06a183e9b907e/src/lexer.c#L295-L308
https://github.com/sysprog21/shecc/blob/affa4fc637b15b4bab7415fbe7a06a183e9b907e/src/lexer.c#L325-L338

I'll submit a patch later to resolve this issue.
