### ISSUE TITLE
Implement basic optimizations

### ISSUE THREAD

**Issue by jserv** [sysprog21/shecc#88]
With the inclusion of SSA in the middle-end, it is now time to implement some common optimizations on the new SSA-based IR. These include constant folding, copy propagation, and dead code elimination.

**Comment by jserv** [comment]
After @vacantron  implements the constant folding optimization, this task will be considered complete, signifying that shecc achieves the goal of implementing a minimal optimizing C compiler capable of compiling itself with proper optimizations.

**Comment by vacantron** [comment]
Should we abjust the directory structure that making `src/ssa.c` focus on building and create another `src/optimizer.c` to include the existent `src/peephole.c` and the other optimizers ?

**Comment by jserv** [comment]
> Should we abjust the directory structure that making `src/ssa.c` focus on building the SSA and create another `src/optimizer.c` to include the existent `src/peephole.c` and the other optimizers ?

Up to you. I expect the availability of basic optimizers existing with minimal efforts.

**Comment by jserv** [comment]
So far, we have implemented a few optimizations:
* Common subexpression elimination
* Constant optimization
* Peephole optimization
* Dead code elimination

With these optimizations complete, we consider this task concluded. Dedicated issues will be created for any additional optimizations as they are planned.
